name: Deploy 
on:
  push:
    branches: [ main ]
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Host
        run: echo "Host:${{ secrets.HOST }}"

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          USERNAME: ubuntu
          HOST: ubuntu@ec2-3-84-84-151.compute-1.amazonaws.com
          PASSWORD: ubuntu@1980
          script: whoami

     

            
      

      
