name: Deploy 
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH Remote Commands
        uses:  appleboy/ssh-action@v1.0.4

      
        with:
          
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GUILD_ID: ${{ secrets.GUILD_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          

      
