name: Deploy 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          # DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          # OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # GUILD_ID: ${{ secrets.GUILD_ID }}
         
          script: whoami
             # cd discord_bot_v14
             # git pull
             # npm i
             # node stop src/app.js
             # node start src/app.js

      
