name: Deploy 
on:
  push:
    branches: [ main ]
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.3
        env:
          USERNAME: ubuntu
          HOST: ${{ secrets.HOST }}
          PASSWORD: ${{ secrets.PASSWORD }
          script: whoami
            
      

      
