name: Deploy 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # - name: SSH Remote Commands
      - name: Run a one_line
        run: echo Hello, world!
        # uses:  appleboy/ssh-action@v1.0.3
        # with:
          # host: ${{ secrets.HOST }}
          # password: ${{ secrets.PASSWORD }}
          # DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          # OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # GUILD_ID: ${{ secrets.GUILD_ID }}
         
          # script: whoami
             # cd discord_bot_v14
             # git pull
             # npm i
             # node stop src/app.js
             # node start src/app.js

      
